require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/enderecos", type: :request do
  
  # Endereco. As you add validations to Endereco, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Endereco.create! valid_attributes
      get enderecos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      endereco = Endereco.create! valid_attributes
      get endereco_url(endereco)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_endereco_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      endereco = Endereco.create! valid_attributes
      get edit_endereco_url(endereco)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Endereco" do
        expect {
          post enderecos_url, params: { endereco: valid_attributes }
        }.to change(Endereco, :count).by(1)
      end

      it "redirects to the created endereco" do
        post enderecos_url, params: { endereco: valid_attributes }
        expect(response).to redirect_to(endereco_url(Endereco.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Endereco" do
        expect {
          post enderecos_url, params: { endereco: invalid_attributes }
        }.to change(Endereco, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post enderecos_url, params: { endereco: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested endereco" do
        endereco = Endereco.create! valid_attributes
        patch endereco_url(endereco), params: { endereco: new_attributes }
        endereco.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the endereco" do
        endereco = Endereco.create! valid_attributes
        patch endereco_url(endereco), params: { endereco: new_attributes }
        endereco.reload
        expect(response).to redirect_to(endereco_url(endereco))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        endereco = Endereco.create! valid_attributes
        patch endereco_url(endereco), params: { endereco: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested endereco" do
      endereco = Endereco.create! valid_attributes
      expect {
        delete endereco_url(endereco)
      }.to change(Endereco, :count).by(-1)
    end

    it "redirects to the enderecos list" do
      endereco = Endereco.create! valid_attributes
      delete endereco_url(endereco)
      expect(response).to redirect_to(enderecos_url)
    end
  end
end
