require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/telefones", type: :request do
  
  # Telefone. As you add validations to Telefone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Telefone.create! valid_attributes
      get telefones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      telefone = Telefone.create! valid_attributes
      get telefone_url(telefone)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_telefone_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      telefone = Telefone.create! valid_attributes
      get edit_telefone_url(telefone)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Telefone" do
        expect {
          post telefones_url, params: { telefone: valid_attributes }
        }.to change(Telefone, :count).by(1)
      end

      it "redirects to the created telefone" do
        post telefones_url, params: { telefone: valid_attributes }
        expect(response).to redirect_to(telefone_url(Telefone.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Telefone" do
        expect {
          post telefones_url, params: { telefone: invalid_attributes }
        }.to change(Telefone, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post telefones_url, params: { telefone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested telefone" do
        telefone = Telefone.create! valid_attributes
        patch telefone_url(telefone), params: { telefone: new_attributes }
        telefone.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the telefone" do
        telefone = Telefone.create! valid_attributes
        patch telefone_url(telefone), params: { telefone: new_attributes }
        telefone.reload
        expect(response).to redirect_to(telefone_url(telefone))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        telefone = Telefone.create! valid_attributes
        patch telefone_url(telefone), params: { telefone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested telefone" do
      telefone = Telefone.create! valid_attributes
      expect {
        delete telefone_url(telefone)
      }.to change(Telefone, :count).by(-1)
    end

    it "redirects to the telefones list" do
      telefone = Telefone.create! valid_attributes
      delete telefone_url(telefone)
      expect(response).to redirect_to(telefones_url)
    end
  end
end
